export const entityFriendlyLabels = {
  zh: { LOCATION:"位置", ORGANIZATION:"组织机构", BANK_ACCOUNT:"银行账户", BANK_CARD:"银行卡号", BANK_CARD_SECURITY_CODE:"银行卡安全码", BANK_CARD_EXPIRY:"银行卡有效期", NATIONAL_ID:"身份证件", GOVERNMENT_ID:"政府证件", TAX_ID:"税号", PASSPORT:"护照", PASSPORT_NUMBER:"护照", DRIVER_LICENSE:"驾驶证", DRIVERS_LICENSE:"驾驶证", VEHICLE_ID:"车辆标识", DEVICE_ID:"设备标识", USERNAME:"用户名", PASSWORD:"密码", PIN:"PIN 码", MAC_ADDRESS:"MAC 地址", USER_AGENT:"用户代理", CRYPTO_ADDRESS:"加密货币地址", DATE_OF_BIRTH:"出生日期" },
  en: { LOCATION:"Location", ORGANIZATION:"Organization", BANK_ACCOUNT:"Bank account", BANK_CARD:"Bank card number", BANK_CARD_SECURITY_CODE:"Bank card security code", BANK_CARD_EXPIRY:"Bank card expiry", NATIONAL_ID:"National ID", GOVERNMENT_ID:"Government ID", TAX_ID:"Tax ID", PASSPORT:"Passport", PASSPORT_NUMBER:"Passport", DRIVER_LICENSE:"Driver's license", DRIVERS_LICENSE:"Driver's license", VEHICLE_ID:"Vehicle identifier", DEVICE_ID:"Device identifier", USERNAME:"Username", PASSWORD:"Password", PIN:"PIN", MAC_ADDRESS:"MAC address", USER_AGENT:"User agent", CRYPTO_ADDRESS:"Cryptocurrency address", DATE_OF_BIRTH:"Date of birth" },
} as const;

export const messages = {
  zh: {
    overview:"概览", logs:"请求日志", services:"服务接入", models:"识别模型", rulesNav:"规则配置", settings:"设置", online:"Core 运行中", offline:"Core 未连接", coreOnline:"Core 运行中", coreOffline:"Core 未连接", desktopOnly:"桌面版才支持 Core 生命周期控制。", reload:"重新加载", uiLoadFailed:"界面加载失败", close:"关闭", scanModels:"扫描模型", tokens:"Token", start:"启动 Core", restart:"重启 Core", stop:"停止 Core",
    overviewTitle:"隐私保护", overviewSub:"所有 AI 请求在离开设备前完成脱敏", logsTitle:"请求日志", logsSub:"检查每次请求的保护状态和实体", testTitle:"脱敏测试", testSub:"输入一段文本，检查规则和模型的脱敏效果", localOnly:"仅在本机处理", servicesTitle:"服务接入", servicesSub:"连接上游模型服务，管理凭证和代理地址", modelsTitle:"识别模型", modelsSub:"切换本地 ONNX 隐私识别模型", rulesTitle:"规则配置", rulesSub:"管理确定性隐私识别规则", settingsTitle:"设置", settingsSub:"管理网关、语言、保护和请求日志",
    protected:"已保护实体", requests:"代理请求", success:"成功率", latency:"平均脱敏耗时", path:"保护能力", local:"本机运行", detection:"识别", gateway:"安全网关", unconfigured:"未配置", capabilityReady:"就绪", capabilityUnavailable:"未就绪", rules:"规则引擎", rulesEngine:"规则引擎", deterministicRules:"确定性规则", ruleCount:"{count} 条规则", localModel:"模型引擎", proxyUrl:"网关地址", autoProxyUrl:"自动匹配网关", proxyMethods:"代理接入方式", serviceIdRoute:"服务 ID", domainRoute:"上游域名", autoRoute:"自动匹配", autoRouteNote:"多个服务匹配时，使用列表中排在最前的一项。", copy:"复制", copied:"已复制",
    activity:"保护活动", activitySub:"请求与识别实体趋势", entities:"实体", distribution:"实体分布", noData:"暂无数据", recent:"最近请求", viewAll:"查看全部", localTest:"脱敏测试", localTestSub:"全部处理均在本机完成，内容不会离开设备", run:"执行脱敏", ready:"等待执行", testInput:"测试内容", testOutput:"脱敏结果", characters:"字符", resetSample:"重置示例", testInputHint:"输入任意包含敏感信息的文本", processing:"正在脱敏…", testEmpty:"执行后在此查看脱敏结果", detectedEntities:"识别到的实体", noEntities:"尚未识别实体",
    search:"搜索服务、路径或打码内容", all:"全部状态", selectRequest:"选择一条请求", selectRequestSub:"查看打码原文、实际发送内容和实体。", summary:"请求概况", protocol:"协议", protection:"保护模式", redacted:"已脱敏", passthrough:"未脱敏转发", protectionDisabled:"全局保护已暂停", passthroughNote:"路径未命中协议配置，请求和响应均已原样转发。", disabledNote:"全局保护关闭期间，请求和响应会原样转发。", duration:"脱敏耗时", traffic:"流量", cachedTokens:"缓存 Token", fieldAudit:"字段审计", originalMasked:"原始信息（已打码）", sentToAI:"发送给 AI",
    addService:"添加服务", configured:"已接入服务", serviceEmpty:"添加服务后，可获得直接替换 SDK base URL 的代理地址。", edit:"编辑", remove:"删除", credential:"凭证", managed:"Remask 托管", pass:"客户端透传", response:"响应处理", restore:"自动还原脱敏内容", redactAIAnswers:"脱敏 AI 回答", redactAIAnswersSub:"提交聊天历史时，也对 assistant/model 角色内容执行脱敏；默认关闭。", save:"保存", cancel:"取消", serviceId:"服务 ID", upstreamUrl:"上游地址", protocolProfile:"请求适配方案", apiKey:"API Key", credentialTemplateNote:"填写 API Key 即可，鉴权 Header 由适配方案自动生成。", profile:"适配方案", credentialSafety:"凭证不会进入请求日志。托管凭证仅保存在本机。", connectionConfig:"接入配置",
    localModels:"本地模型", active:"活动", available:"可用", invalid:"错误", activate:"启用", unload:"卸载", runtime:"运行库", quantization:"量化", version:"版本", sequence:"序列长度", validation:"包校验", valid:"Manifest、大小和 SHA-256 校验通过", modelSpecs:"模型规格", modelCatalog:"模型下载", downloadModel:"下载模型", manualModelDownload:"从 Hugging Face 下载", huggingFaceProject:"项目地址", download:"下载", modelDownloads:"模型下载", modelDownloadsSub:"模型文件来源和网络镜像。", hfMirror:"Hugging Face 镜像", hfMirrorSub:"留空使用官方地址；例如 https://hf-mirror.com",
    gatewaySettings:"网关", gatewaySettingsSub:"设置应用接收 AI 请求的端口。", interfaceSettings:"界面", interfaceSettingsSub:"选择应用显示语言。", gatewayPort:"监听端口", gatewayPortSub:"输入完成后生效；桌面版会自动重启 Core", gatewayPortInvalid:"网关端口必须为 1–65535，且不能与 Core 端口相同", language:"显示语言", autoSaveNote:"设置改动后立即生效", saveSettings:"保存更改", saveSettingsSub:"一次保存本页全部更改", settingsSaved:"更改已保存", settingsSavedRestarted:"更改已保存，Core 已重启", protectionSettings:"隐私保护", protectionSettingsSub:"决定哪些提交内容需要脱敏。", audit:"请求日志", auditSub:"控制日志记录范围和保留时间。", record:"记录请求日志", recordSub:"关闭后不再新增日志", retention:"保留时间", retentionSub:"到期日志自动清理", clearLogs:"清空日志", saveAudit:"保存更改", confirmDelete:"删除此服务？", confirmClear:"清空全部本地请求日志？此操作无法撤销。", confirm:"确认", error:"操作失败", streaming:"流式", days:"天", globalProtection:"请求保护", protectionOn:"隐私保护中", protectionOff:"隐私保护已暂停", protectionOnSub:"AI 请求离开本机前自动脱敏", protectionOffSub:"请求将不经脱敏直接转发", tokenUsage:"Token 用量", inputTokens:"输入", outputTokens:"输出", totalTokens:"合计", entityCount:"脱敏实体", entityProtection:"模型实体脱敏", entityProtectionSub:"控制模型识别出的敏感信息类型；普通规则由各自开关控制", customRules:"自定义规则", expression:"正则表达式", addRule:"添加规则", saveRules:"保存规则", ruleId:"规则 ID", enabled:"已启用", deterministicRuleNote:"普通规则使用 <MASK_大写规则ID:四位码> 标签；模型标签保持实体类型格式。", entityPerson:"姓名", entityPhone:"电话号码", entityEmail:"电子邮箱", entityAddress:"地址", entityPrivateDate:"私密日期", entityAccount:"账户号码", entityIp:"IP 地址", entitySecret:"密钥与凭证", entityUrl:"网址", entityCustom:"自定义实体"
  },
  en: {
    overview:"Overview", logs:"Request log", services:"Service connections", models:"Detection models", rulesNav:"Rules", settings:"Settings", online:"Core running", offline:"Core disconnected", coreOnline:"Core online", coreOffline:"Core offline", desktopOnly:"Core lifecycle controls are available in the desktop app.", reload:"Reload", uiLoadFailed:"The interface failed to load", close:"Close", scanModels:"Scan models", tokens:"tokens", start:"Start Core", restart:"Restart Core", stop:"Stop Core",
    overviewTitle:"Privacy protection", overviewSub:"Every AI request is redacted before it leaves this device", logsTitle:"Request log", logsSub:"Inspect protection status and entities for every request", testTitle:"Redaction test", testSub:"Enter text to check how rules and models redact it", localOnly:"Processed locally", servicesTitle:"Service connections", servicesSub:"Connect upstream model services and manage credentials and proxy URLs", modelsTitle:"Detection models", modelsSub:"Switch local ONNX privacy detection models", rulesTitle:"Rules", rulesSub:"Manage deterministic privacy detection rules", settingsTitle:"Settings", settingsSub:"Gateway, language, protection, and request logs",
    protected:"Protected entities", requests:"Proxy requests", success:"Success rate", latency:"Average redaction time", path:"Protection capabilities", local:"Local", detection:"Detection", gateway:"Security gateway", unconfigured:"Not configured", capabilityReady:"Ready", capabilityUnavailable:"Unavailable", rules:"Rules only", rulesEngine:"Rules engine", deterministicRules:"Deterministic rules", ruleCount:"{count} rules", localModel:"Model engine", proxyUrl:"Gateway URL", autoProxyUrl:"Auto-routing gateway", proxyMethods:"Proxy connection methods", serviceIdRoute:"Connection ID", domainRoute:"Upstream domain", autoRoute:"Automatic match", autoRouteNote:"When multiple connections match, the first one in the list is used.", copy:"Copy", copied:"Copied",
    activity:"Protection activity", activitySub:"Request and entity trends", entities:"Entities", distribution:"Entity distribution", noData:"No data yet", recent:"Recent requests", viewAll:"View all", localTest:"Redaction test", localTestSub:"Everything is processed locally and content never leaves this device", run:"Run redaction", ready:"Ready", testInput:"Test content", testOutput:"Redacted result", characters:"characters", resetSample:"Reset sample", testInputHint:"Enter any text containing sensitive information", processing:"Redacting…", testEmpty:"Run the test to see the redacted result", detectedEntities:"Detected entities", noEntities:"No entities detected yet",
    search:"Search service, path, or masked content", all:"All statuses", selectRequest:"Select a request", selectRequestSub:"Inspect masked input, AI-bound content, and entities.", summary:"Request summary", protocol:"Protocol", protection:"Protection mode", redacted:"Redacted", passthrough:"Unredacted passthrough", protectionDisabled:"Protection paused", passthroughNote:"This path did not match the protocol profile. Request and response were forwarded unchanged.", disabledNote:"Requests and responses are forwarded unchanged while global protection is paused.", duration:"Redaction time", traffic:"Traffic", cachedTokens:"cached tokens", fieldAudit:"Field audit", originalMasked:"Original (masked)", sentToAI:"Sent to AI",
    addService:"Add service", configured:"Connected services", serviceEmpty:"Add a service to get a drop-in SDK base URL.", edit:"Edit", remove:"Delete", credential:"Credential", managed:"Managed by Remask", pass:"Passed by client", response:"Response handling", restore:"Restore protected content", redactAIAnswers:"Redact AI answers", redactAIAnswersSub:"Also redact assistant/model content in submitted history. Off by default.", save:"Save", cancel:"Cancel", serviceId:"Service ID", upstreamUrl:"Upstream URL", protocolProfile:"Request adapter", apiKey:"API key", credentialTemplateNote:"Enter the API key only. The adapter generates the authentication headers.", profile:"Adapter", credentialSafety:"Credentials never enter request logs. Managed credentials remain local.", connectionConfig:"Connection settings",
    localModels:"Local models", active:"Active", available:"Available", invalid:"Invalid", activate:"Activate", unload:"Unload", runtime:"Runtime", quantization:"Quantization", version:"Version", sequence:"Sequence length", validation:"Package validation", valid:"Manifest, size, and SHA-256 checks passed", modelSpecs:"Model specifications", modelCatalog:"Model downloads", downloadModel:"Download model", manualModelDownload:"Download from Hugging Face", huggingFaceProject:"Project URL", download:"Download", modelDownloads:"Model downloads", modelDownloadsSub:"Model sources and network mirror.", hfMirror:"Hugging Face mirror", hfMirrorSub:"Leave blank for the official endpoint; for example https://hf-mirror.com",
    gatewaySettings:"Gateway", gatewaySettingsSub:"Set the port that accepts AI requests.", interfaceSettings:"Interface", interfaceSettingsSub:"Choose the application language.", gatewayPort:"Listening port", gatewayPortSub:"Applies when editing finishes; the desktop app restarts Core automatically", gatewayPortInvalid:"Gateway port must be 1–65535 and different from the Core port", language:"Display language", autoSaveNote:"Settings apply immediately after a change", saveSettings:"Save changes", saveSettingsSub:"Save all changes on this page together", settingsSaved:"Changes saved", settingsSavedRestarted:"Changes saved and Core restarted", protectionSettings:"Privacy protection", protectionSettingsSub:"Choose which submitted content is redacted.", audit:"Request logs", auditSub:"Control log capture and retention.", record:"Record request logs", recordSub:"No new logs are added while disabled", retention:"Retention", retentionSub:"Expired logs are removed automatically", clearLogs:"Clear logs", saveAudit:"Save changes", confirmDelete:"Delete this service?", confirmClear:"Clear all local request logs? This cannot be undone.", confirm:"Confirm", error:"Action failed", streaming:"Streaming", days:"days", globalProtection:"Request protection", protectionOn:"Privacy protection on", protectionOff:"Privacy protection paused", protectionOnSub:"AI requests are redacted before leaving this device", protectionOffSub:"Requests are forwarded without redaction", tokenUsage:"Token usage", inputTokens:"Input", outputTokens:"Output", totalTokens:"Total", entityCount:"Redacted entities", entityProtection:"Model entity redaction", entityProtectionSub:"Control entity types detected by models; regular rules use their own switches", customRules:"Custom rules", expression:"Regular expression", addRule:"Add rule", saveRules:"Save rules", ruleId:"Rule ID", enabled:"Enabled", deterministicRuleNote:"Regular rules use <MASK_UPPERCASE_RULE_ID:HEX4>; model labels retain the entity-type format.", entityPerson:"Person name", entityPhone:"Phone number", entityEmail:"Email address", entityAddress:"Address", entityPrivateDate:"Private date", entityAccount:"Account number", entityIp:"IP address", entitySecret:"Secrets & credentials", entityUrl:"Web address", entityCustom:"Custom entity"
  }
} as const;
export type Locale = keyof typeof messages;
export type MessageKey = keyof typeof messages.zh;
