import { Box, CheckCircle2, Cpu, RefreshCw } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { coreApi } from "../../shared/api/client";
import type { BootstrapData } from "../../shared/api/types";
import { useApp } from "../../app/AppContext";
import { useI18n } from "../../shared/i18n/I18n";
import { Badge, StatusDot } from "../../shared/ui/Status";
import { Button } from "../../shared/ui/Button";

export function Models({data}:{data:BootstrapData}){const {t}=useI18n();const {notify}=useApp();const qc=useQueryClient();const [selected,setSelected]=useState(data.activeModel?.id||data.models[0]?.id||"");const current=data.models.find(x=>x.id===selected)||data.models[0];const scan=useMutation({mutationFn:coreApi.scanModels,onSuccess:()=>qc.invalidateQueries()});const unload=useMutation({mutationFn:coreApi.unloadModel,onSuccess:()=>qc.invalidateQueries()});const activate=useMutation({mutationFn:coreApi.activateModel,onSuccess:async result=>{for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,500));const op=await coreApi.operation(result.operation_id);if(op.status==="succeeded"){qc.invalidateQueries();return}if(op.status==="failed")throw new Error(op.error)}},onError:e=>notify(String(e))});
return <div className="split-view"><section className="list-pane"><div className="pane-title"><div><span>{t("localModels")}</span><small>{data.runtime.name}</small></div><Button size="icon" variant="ghost" onClick={()=>scan.mutate()} aria-label="Scan models"><RefreshCw size={14}/></Button></div><div className="model-list">{data.models.map(item=><button key={item.id} className={current?.id===item.id?"selected":""} onClick={()=>setSelected(item.id)}><span className="model-icon"><Box size={16}/></span><div><strong>{item.manifest.name||item.id}</strong><code>{item.id}</code><small>{item.manifest.quantization} · {item.manifest.max_tokens} tokens</small></div><StatusDot tone={item.active?"success":item.valid?"muted":"error"}/></button>)}</div></section><section className="detail-pane">{current&&<><header className="detail-header"><div><span>{current.active?t("active"):t("models")}</span><h2>{current.manifest.name}</h2><code>{current.id}</code></div>{current.active?<Button variant="danger" onClick={()=>unload.mutate(current.id)}>{t("unload")}</Button>:<Button variant="primary" disabled={!current.valid||!data.runtime.available||activate.isPending} onClick={()=>activate.mutate(current.id)}>{t("activate")}</Button>}</header><section className="model-hero"><div className="model-hero__icon"><Cpu size={25}/></div><div><span>{t("runtime")}</span><strong>{data.runtime.name}</strong><small>{current.manifest.quantization} · {current.manifest.label_scheme}</small></div>{current.active&&<Badge tone="success">{t("active")}</Badge>}</section><section className="detail-section"><h3>{t("summary")}</h3><dl className="property-grid"><div><dt>{t("runtime")}</dt><dd>{data.runtime.name}</dd></div><div><dt>{t("quantization")}</dt><dd>{current.manifest.quantization}</dd></div><div><dt>{t("version")}</dt><dd><code>{current.manifest.version}</code></dd></div><div><dt>{t("sequence")}</dt><dd>{current.manifest.max_tokens} / stride {current.manifest.stride}</dd></div></dl></section><section className="detail-section"><h3>{t("validation")}</h3>{current.valid?<div className="validation-ok"><CheckCircle2 size={16}/>{t("valid")}</div>:current.errors.map(e=><p className="validation-error" key={e}>{e}</p>)}</section></>}</section></div>}
